config/routes.rb
Rails.application.routes.draw do

  resources :home , defaults: {format: :json}
  root to: 'application#index'
  get 'home/show_application/:id'  => 'home#show_application' , defaults: {format: :json}

  get '/auth/odesk/callback', to: 'sessions#create', via: [:get, :post]

  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base

	def self.from_omniauth(auth)

    if auth.present?
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
  end

end

app/controllers/application_controller.rb
require 'rubygems'
require 'oauth'
require 'json'


class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
 
  after_filter :set_csrf_cookie_for_ng
    layout = 'application'
  def index
    render  text: '' , layout: true
  end


  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected
  
    def verified_request?
      super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
    end
 private

   def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end
   helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  respond_to :json


  # List the all application/job on index page which posted by User 
  def index
    if $data.present?
      @data ||=  $data.get('/api/hr/v2/jobs.json?buyer_team__reference='+company_reference).read_body
    end
    if @data.present?
      @applications = get_hash(@data)["jobs"]["job"]
      respond_with(@applications)
    else
      respond_with(User.all)
    end
  end

 
  # it will show all applicants list which applied for particular contract or job
  def show_application
    @grp_data = {}
    status = ["hidden","shortlisted","messaged","hired","declined","offered"]
    if $data.present?
      @data =  $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference).read_body
      # for i in (0..(status.length-1))
      #    @grp_data[status[i]] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference).read_body
      # end

       @grp_data["hidden"] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference+'&status=hidden').read_body
       @grp_data["shortlisted"] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference+'&status=shortlisted').read_body
       @grp_data["messaged"] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference+'&status=messaged').read_body
       @grp_data["hired"] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference+'&status=hired').read_body
       @grp_data["declined"] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference+'&status=declined').read_body
       @grp_data["offered"] = $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:id]+'&buyer_team__reference='+company_reference+'&status=offered').read_body


    end
  

    if @data.present?
      @applicaiton = get_hash(@data)["applications"]
      for i in (0..(status.length))
        if i==6
          @grp_data["all"] = @applicaiton
        else
         @grp_data[status[i]] = get_hash(@grp_data[status[i]])["applications"]
        end 
      end
    # binding.pry
      # @myar1 = []
      #  @applicaiton.each do |key|
      #    if key["is_shortlisted"]=="1"
      #     h = {}
      #     h = key
      #     @myar1 << h
      #    end
      #  end
      #  @grp_data["shortlisted"] = @myar1
       @grp_data["all"] = @applicaiton


      #binding.pry
       ar = []
       ar << @grp_data
       respond_with(ar)
    else
      #binding.pry
      respond_with(User.all)
    end
  end

 
  # it show contractractor/ applicants detail 
  def show
    
    if $data.present?
      @data ||=  $data.get('/api/hr/v3/clients/applications/'+params[:id]+'.json?buyer_team__reference='+company_reference).read_body
    end

    if @data.present?
      @application = get_hash(@data)["application"]
      arr = []
      arr << @application
       respond_with(arr)
    end

  end

 # def destroy
    
  #  if $data.present?
  #     @data ||=  $data.get('/api/hr/v3/clients/applications.json?job_key='+params[:job_key]+'&buyer_team__reference='+company_reference).read_body
  #   end
  #   if @data.present?
  #     @applicaiton = get_hash(@data)["applications"]
  #     respond_with(@applicaiton)
  #   end
  # end

  private


  # return Company Reference id for access data
  def company_reference
     @company_data = $data.get('/api/hr/v2/companies.json').read_body
     @c_ref = JSON.parse(@company_data)["companies"].first["reference"]
     return @c_ref
  end

  # it convert the Data in Json format for showing them.
  def get_hash(data)
     @hash_data = JSON.parse(data)
     return @hash_data
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 

  # create session with new User or Existing user
  def create
  
    user = User.from_omniauth(env["omniauth.auth"])
    if user.present?
      session[:user_id] = user.id 
      $data = env["omniauth.auth"].extra.access_token
    end
    redirect_to  root_path
 

  end


  # destroy the session for User 
  def destroy
    session[:user_id] = nil
    redirect_to '/#'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

app/views/home/create.html.haml
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

app/views/home/index.html.haml
- if current_user
  %h1 
    Apllications List
  %div{"ng-controller" => "AllDataController"}
    %table#my-table.table{:border => "0", :style => "border-collapse:collapse"}
      %thead
        %tr
          %td 
            skills
          %td
            category
          %td     
            created_time
          %td
            title
          %td 
            reference
      %tbody
        {{stocks}}
        %tr{"data-ng-repeat" => "value in stocks"}
          %td {{value.skills}}
          %td {{value.category}}
          %td {{value.created_time}}
          %td {{value.title}}
          %td 
            %a{:href => "", "ng-click" => "deleteStock(value.reference, $index)"} {{value.reference}}
  

:javascript
  $(function() {   
    $(".filter").change(function(){
      var col_id = $(this).attr("id");
       $("#my-table td.col_"+col_id+":contains('" + $(this).val() + "')").parent().show();
       $("#my-table td.col_"+col_id+":not(:contains('" + $(this).val() + "'))").parent().hide();
    }); 
  });

app/views/home/new.html.erb
<h1>Home#new</h1>
<p>Find me in app/views/home/new.html.erb</p>

app/views/home/new.html.haml
hiiiiiiii

app/views/home/show.html.haml
%h1= @application["contractor_name"]
%table.table{:border => "0"}
  - @application.each do |key , value|
    %tr
      %td{:class => "col_#{@value}"}
        %b
          = "#{key}"
      %td{:class => "col_#{@value}"}
        = "#{value}".html_safe

app/views/home/show_application.html.haml
%h1 
  Applicants List
- if @applicaiton.present?
  %table#my-table.table{:border => "0", :style => "border-collapse:collapse"}
    %thead
      %tr
        - val = 0
        - @applicaiton.first.each do |key , value|
          - if key == "rid" || key == "job_type" || key == "contractor_name" || key == "contractor_title" || key == "created_type"
            %th
              %input.filter{:id => val, :placeholder => "Filter ", :type => "text"}/
              - val=val+1
      %tr
        - @applicaiton.first.each do |key , value|
          - if key == "rid" || key == "job_type" || key == "contractor_name" || key == "contractor_title" || key == "created_type"
            %th
              = key.capitalize
    %tbody
      - @applicaiton.each do |key , value|
        %tr
          - @value=0
          - key.each do |k,v|
            - if k == "rid" || k == "job_type" || k == "contractor_name" || k == "contractor_title" || k == "created_type"
              %td{:class => "col_#{@value}"}
                - if k == "rid"
                  = link_to "#{v}" , home_show_path(:app => v)
                - else
                  = "#{v}".html_safe
                - @value=@value+1
:javascript
  $(function() {   
  	$(".filter").change(function(){
  		var col_id = $(this).attr("id");
  		 $("#my-table td.col_"+col_id+":contains('" + $(this).val() + "')").parent().show();
       $("#my-table td.col_"+col_id+":not(:contains('" + $(this).val() + "'))").parent().hide();
    }); 
  });
 

app/views/layouts/application.html.haml
%html{"ng-app" => "OdeskLogin"}
  %head
    %title OdeskLogin
    %script{:src => "//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"}
    %script{:src => "//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'bootstrap'
    = javascript_include_tag 'bootstrap'
    = csrf_meta_tags
  %body
    #user-widget
      .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "#"} HAYDEN
          %center
            .navbar-collapse.collapse.col-sm-6.navbar-form
              %input#kwd_search.form-control{:placeholder => "Search", :type => "text", :value => ""}/
          .navbar-collapse.collapse
            %form.navbar-form.navbar-right{:role => "form"}
              - if current_user
                Welcome
                = succeed "!" do
                  %strong= current_user.name
                = link_to "Sign out", signout_path, id: "sign_out", :class=>"btn btn-success"
              - else
                = link_to "OdeskLogin", "/auth/odesk", id: "sign_in", :class=>"btn btn-success"
          / /.navbar-collapse
      / Main jumbotron for a primary marketing message or call to action
      .jumbotron
        .container
          .navbar.navbar-static-top
            - if current_user
              #loading
                %b Loading...
      .container
        - if current_user
          %div{"ng-view" => "ng-view"}
        / Example row of columns
        .row
          = yield

        %hr
          %footer
            %p &copy; Company 2014
      / /container
 